pipeline{
    agent any

    stages{
        stage("Initialize terraform"){
            steps{
                dir("eks"){
                    sh "terraform init"
                }
            }
        }

        stage("Validate terraform"){
            steps{
                dir("eks"){
                    sh "terraform validate"
                }
            }
        }

        stage("Plan terraform"){
            steps{
                dir("eks"){
                    sh "terraform plan"
                }
                input(message: "Do you want to continue?", ok: "Proceed")
            }
        }

        stage("Destroy/Apply EKS Cluster"){
            steps{
                dir("eks"){
                    sh "terraform $action -auto-approve"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}